projectarms/arms/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

#paths arranged alphabetically by name
app_name = 'arms'
urlpatterns = [ 
    # path('api/data', views.get_data, name='api-data'),

    #TEST URL
    path('dashboard/', views.ArmsAdminView.as_view(), name="arms_admin_view"),
    path('homepage/', views.HomepageView.as_view(), name="homepage_view"),
    path('profile/', views.ProfileIndexView.as_view(), name='profile_view'),
    path('landingpage/', views.LandingPageIndexView.as_view(), name='landingpage_view'),
    path('register/', views.registerPage, name='register_view'),
    path('logout/', views.logoutPage, name='logout_view'),
    path('aboutUs/', views.AboutUsIndexView.as_view(), name='aboutUs_view'),
    path('addbook/', views.AddBookIndexView.as_view(), name='addBook_view'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projectarms/projectarms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('arms/', include('arms.urls', namespace='arms'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projectarms/arms/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class User(models.Model):
	name = models.CharField(max_length=200, null=True)
	phone = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)

	profile_pic = models.ImageField(upload_to='media/')

	def __str__(self):
		return self.name

class Author(models.Model):
	# book_author_id = models.CharField(primary_key=True, max_length=50)
	book_author_id = models.AutoField(primary_key=True)
	firstname = models.CharField(max_length = 100, null=True)
	lastname = models.CharField(max_length = 100)
	email = models.CharField(max_length = 100)
	birthdate = models.DateField(default = timezone.now)
	G_CHOICES = [('M','Male'),('F','Female')]
	gender=models.CharField(max_length = 50, choices=G_CHOICES)

	class Meta:
		db_table = "Author"
		verbose_name_plural = "Authors"

class Category(models.Model):
	# book_category_no = models.CharField(primary_key=True, max_length=50)
	book_category_no = models.AutoField(primary_key=True)
	book_category = models.CharField(max_length=100)

	class Meta:
		db_table = "Category"
		verbose_name_plural = "Categories"

class Books(models.Model):
	# book_id = models.CharField(primary_key=True, max_length=50)
	book_id = models.AutoField(primary_key=True)
	book_title = models.CharField(max_length = 500)
	book_author = models.ForeignKey(Author, on_delete=models.CASCADE, default = "", related_name="author")
	book_cover = models.ImageField(upload_to='media/')
	book_file = models.FileField(upload_to='media/')
	book_year = models.DateField()
	book_tags = models.CharField(max_length = 100)
	book_summary = models.CharField(max_length = 500)
	book_category = models.ForeignKey(Category, on_delete=models.CASCADE, default = "",  related_name="category")
	date_added = models.DateField(default=timezone.now)
	book_info = models.CharField(max_length = 500, default="")
	readCount = models.IntegerField(default=0)
	bookmarkCount = models.IntegerField(default=0)
	downloadCount = models.IntegerField(default=0)

	is_bookmarked = models.BooleanField(default=False)
	is_downloaded = models.BooleanField(default=False)
	is_read = models.BooleanField(default=False)
	is_deleted= models.BooleanField(default=False)
	
	class Meta:
		db_table = "Books"
		verbose_name_plural = "Books"

projectarms/arms/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from arms.models import Books, Author, Category

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['first_name','last_name','username', 'email', 'password1', 'password2']

class AuthorForm(forms.ModelForm):

 	class Meta:
 		model = Author
 		fields=('firstname','lastname','birthdate','email')

class BooksForm(forms.ModelForm):

 	class Meta:
 		model = Books
 		fields = ('book_title','book_author','book_cover','book_file','book_year','book_tags','book_summary','book_category',)
 		# fields = '__all__'

class CategoryForm(forms.ModelForm):

 	class Meta:
 		model = Category
 		fields=('book_category',)

projectarms/arms/views.py
import datetime
from .forms import *
from .models import *
from .forms import CreateUserForm
from itertools import chain
from django.shortcuts import render,redirect
from django.views.generic import View
from django.http import HttpResponse, Http404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q, Count, Max, Min
from django.core.paginator import Paginator, EmptyPage
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
import pyttsx3
import speech_recognition as sr 
# import xlrd
# import mysql.connector

# Create your views here.
# 1 Makemigrations
# 2 Migrate
# 3 Createsuperuser for django admin
# 4 Go to register page 
# 5 Fill out details, password dpat tarong kay mo error sya
# 6 Check django admin if nasuod sya
# 7 Login, pero dle pa sya mo redirect sa page

def logoutPage(request):
	logout(request)
	return redirect('arms:landingpage_view')

def registerPage(request):
	form = CreateUserForm()
	if request.method == 'POST':
		form = CreateUserForm(data=request.POST)
		# print(form.is_valid())
		# print(form.errors)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username')
			# messages.success(request,'Account was created for '+user)
			messages.success(request, 'Registration Successful')
			return redirect('arms:landingpage_view')

	context = {'form':form}
	return render(request,'register.html',context)
def logoutPage(request):
	logout(request)
	return redirect('arms:landingpage_view')

# pagination 
def pageResults(request, x):
	p = Paginator(x,20)
	page_num = request.GET.get('page', 1)
	try:
		page = p.page(page_num)
	except:
		page = p.page(1)

	return page

#By category searched of all books function
def category_search(request, searched):
	arr = ['Research','Journal','Filipiniana','Engineering','Computer Science','Information Technology','Business','Architecture']
	length = len(arr)
	i=0
	searched = searched.capitalize()
	while i<length:
		if searched == arr[i]:
			ctgy = Category.objects.get(book_category = searched)
			print(ctgy)
			# for c in ctgy:
			books = Books.objects.filter(Q(book_category_id=ctgy.book_category_no))
			authors = Author.objects.all()
			category = Category.objects.all()
			context={
				'authors' : authors,
				# 'books' : books,
				'books' : pageResults(request, books),
				'search' : searched,
				'category' : category,
			}
			return render(request, 'results.html', context)
		else:
			i+=1

	return render(request, 'results.html', {'search' : searched})	

def author_category_search(request, searched, param):
	searched = searched
	param = param
	authors = Author.objects.get(Q(firstname__icontains=searched) & Q(lastname__icontains=param))
	# for author in authors:
	if authors:
		books = Books.objects.filter(book_author_id=authors.book_author_id)
		category = Category.objects.all()
		x = Author.objects.all()
		context={
			'search' : searched + ' ' + param + "'s Works",
			'books' : pageResults(request, books),
			'authors' : x,
			'category' : category,
		}
		return render(request, 'results.html', context)
	else:
		# return category_search(request, searched)
		return render(request, 'results.html', {'search' : searched + ' ' + param + "'s Works"})

def author_search(request, search):
	search = search 
	category = Category.objects.all()
	x = Author.objects.all()
	authors = Author.objects.filter(Q(firstname__icontains=search) | Q(lastname__icontains=search))
	for author in authors:
		# if the author is found then it will proceed to search for the book that was written by the author
		books = Books.objects.filter(book_author_id=author.book_author_id)		
		context={
			'search' : search,
			'books' : pageResults(request, books),
			'authors' : x,
			'category' : category,
		}
		return render(request, 'results.html', context)

	return category_search(request, search)

def bookTitle_search(request, search):
	print(search)
	search = search
	books = Books.objects.filter(Q(book_title__icontains=search) | Q(book_year__icontains=search))
	if books:
		category = Category.objects.all()
		authors = Author.objects.all()
		context={
			'search' : search,
			'books' : pageResults(request, books),
			'authors' : authors,
			'category' : category,
		}
		return render(request, 'results.html', context)
	else:
		# if the user tries to search using the authors first or last name
		return author_search(request, search) 

def newReleases(request):
	# new releases within the month of the year (more or less): days is disregarded
	today = datetime.date.today()
	books = Books.objects.filter(date_added__year=today.year, date_added__month=today.month)
	authors = Author.objects.all()
	category = Category.objects.all()
	popular = popularBooks(request,books)
	context={
		'month' : today.strftime('%B'),
		'popular': popular,
		'books' : books,
		'authors' : authors,
		'category' : category,
	}
	return render(request, 'homepage.html', context)

def popularBooks(request,y):
	maxValue = y.aggregate(Max('readCount'))
	minValue = y.aggregate(Min('readCount'))
	allBooks = y.filter(Q(readCount__gt=minValue['readCount__min']) & Q(readCount__lte=maxValue['readCount__max']))
	return allBooks

def count (request):
	#is_read = 0
	#for read in range(len(readBooks)):
		#if readBooks[read] == to_find:
			#is_read += 1
	#return is_read

	readBooks = Books.objects.filter(is_read= '1').count()

	context = {
		'readBooks': readBooks
	}
	print(readBooks)

def speak(audio): 
      
    engine = pyttsx3.init() 
    # current value of engine property
    voices = engine.getProperty('voices') 
      
    # [0] = Male voice
    # [1] = Female voice 
    engine.setProperty('voice', voices[1].id) 
      
    # Method for the speaking of the the assistant 
    engine.say(audio)   
      
    # Blocks while processing all the currently 
    # queued commands 
    engine.runAndWait()


def Take_query(request): 
    while(True): 
        query = takeCommand(request).capitalize()

        if "Hey jane" in query: 
            speak("Good Day! I'm jane. What do you want to search?")
        elif "Thank you" in query: 
            speak("My pleasure. Call me if you need anything.") 
            break
        elif query:
        	search = query
        	speak("here are the results for" + search)
        	return bookTitle_search(request, search)
          
def takeCommand(request):
    r = sr.Recognizer() 

    with sr.Microphone() as source: 
        print('Listening')
          
        r.adjust_for_ambient_noise(source, duration=0.2)
        audio = r.listen(source)
        try: 
            print("Recognizing")
            Query = r.recognize_google(audio, language='en') 
            print("the command is printed=", Query)

        except Exception as e: 
            print(e) 
            speak("I'm sorry, I didn't get that. Please say it again.")
            return takeCommand(request)

        return Query


def Hello(request): 
    speak("Hi! I am Jane , your library assistant. What do you want to search?")

class ArmsAdminView(View):
	#@staff_member_required(redirect_field_name='next', login_url='arms:landingpage_view')#If the user is logged in,is a staff member (User.is_staff=True),and is active (User.is_active=True),execute the view normally.
	def get(self, request):
		books = Books.objects.select_related('book_author', 'book_category').filter(is_deleted=False).all()
		#bookcategory= Books.objects.get(book_category_id)
		users = User.objects.all()
		#authors = Author.objects.all()
		#category = Category.objects.all() #get(pk=9) #filter(book_category_no=bookcategoryno)
		Totalbooks = Books.objects.filter(is_deleted=False).count()
		Totalusers = User.objects.count()
		context={
			'books' : books,
			'users' : users,
		#	'authors' : authors,
		#	'category' : category,
			'Totalbooks' : Totalbooks,
			'Totalusers' : Totalusers,
		}
		return render(request,'admindashboard.html', context)
	
	#@staff_member_required(redirect_field_name='next', login_url='arms:landingpage_view')
	def post(self, request):
		if request.method == 'POST':	
			if 'btnUpdateUser' in request.POST:	
				print('update user profile button clicked')
				userid = request.POST.get("userid")
				username = request.POST.get("username")			
				firstname = request.POST.get("firstname")
				lastname = request.POST.get("lastname")
				email = request.POST.get("email")
				
				update_user = User.objects.filter(id = userid)
				update_user.update(username=username,first_name=firstname,last_name=lastname,email=email)
				
				print(update_user)
				print('profile updated')

			elif 'btnDeleteUser' in request.POST:	
				print('delete user button clicked')
				userid = request.POST.get("userid")
				delete_user = User.objects.filter(id=userid)
				delete_user.delete()
				print('record deleted')

			elif 'btnUpdateBook' in request.POST:	
				print('update book button clicked')
				bookid = request.POST.get("bookid")
				booktitle = request.POST.get("booktitle")
				bookyear = request.POST.get("bookyear")
				booksummary = request.POST.get("booksummary")
				booktags = request.POST.get("booktags")

				bookcategoryno = request.POST.get("bookcategoryno")
				bookcategory = request.POST.get("bookcategory")

				authorid = request.POST.get("authorid")
				authorfname = request.POST.get("authorfname")
				authorlname = request.POST.get("authorlname")
				authoremail = request.POST.get("authoremail")
				authorbdate = request.POST.get("authorbdate")
				authorgender = request.POST.get("authorgender")

				update_book = Books.objects.filter(book_id = bookid)
				update_book.update(book_title = booktitle, book_year=bookyear, book_summary=booksummary, book_tags=booktags)

				update_category = Category.objects.filter(book_category_no=bookcategoryno)
				update_category.update(book_category=bookcategory)

projectarms/arms/templates/aboutUsPage.html
{% extends "base.html" %}
{% block content %}
<div class ="section">
    <div class="left-section">
        <div class="content">
            <div class="title">
            <h1>About Us</h1>
            </div>
            <p>is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
            when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            It has survived not only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged.</p>
            <br>
                <h6><b>Contact Info</b></h6>
                arms@cit.edu<br>
                +23232323
        </div>
    </div>
</div>
<div class="bookimg">
    <img src="./../static/images/book.png" width="300px"height="300px" alt="" class="d-inline-block align-middle mr-2">
</div>
{% endblock content %}

projectarms/arms/templates/base.html
<!-- FOR HOMEPAGE, LANDING PAGE -->

{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% if title %}
        <title>ARMS - {{ title }}</title>
        {% else %}
        <title>Archived of Reading Materials</title>
        {% endif %}
        <!--All CSS links here-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.css">
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <!-- <link rel="stylesheet" href="{% static 'css/homepage.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body id="page-top">
        {% if user.is_authenticated %}
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
          <img src="{% static 'images/cit1.png' %}" width="80">
          <img src="{% static 'images/logo5.png' %}" width="100">
          <a class="navbar-brand js-scroll-trigger text-center" href="#page-top">  Archived of Reading Materials </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#page-top">Home</a></li>
                        <li class="nav-item">
                          <div class="dropdown show">
                            <a class="btn dropbtn btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="position:relative; z-index:1; top:-4px; right:-10px; padding:0px;">
                                Hi, {{ username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                              <a class="dropdown-item" href='{% url "arms:profile_view" %}'>Profile</a>
                              <a class="dropdown-item" href='{% url "arms:logout_view" %}' >Log out</a>
                            </div>
                          </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h2 class="text-uppercase text-white font-weight-bold">Welcome to Archived of Reading Materials</h2>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#homepage">Click here to browse books</a>
                    </div>
                </div>
            </div>
        </header>
        {% else %}
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
            <img src="{% static 'images/cit1.png' %}" width="80">
            <img src="{% static 'images/logo5.png' %}" width="100">
            <a class="navbar-brand js-scroll-trigger text-center" href="#page-top">  Archived of Reading Materials </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#page-top">Home</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Feeding your brain with Knowledge</h1>
                        <hr class="divider my-4">
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#login">LOG IN HERE</a>
                            
                    </div>
                </div>
            </div>
        </header>

         <!-- Login-->
        <section class="page-section" id="login">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2 class="mt-0">LOGIN</h2>
                        <hr class="divider my-4" />
                        <div class= "panel-transparent">
                            <div class= "login-body">
                                <form method="POST" action="">
                                    {% csrf_token %}
                                    <div class="txt_field">
                                        <!-- <input type="text" name="username" > -->
                                        <input class="w-100" type="text" name="username" maxlength="150" required="" id="id_username">
                                        <span></span>
                                        <label>Username</label>
                                    </div>
                                    <div class="txt_field">
                                        <!-- <input type="password" name="password"> -->
                                        <input class="w-100" type="password" name="password" autocomplete="new-password" required="" id="id_password">
                                        <span></span>
                                        <label>Password</label>
                                    </div>
                                    <!-- <div class="pass">Forgot Password?</div> -->
                                    <input type="submit" value="LOGIN">
                                    {% for message in messages %}
                                        <p id="messages">{{message}}</p>
                                    {% endfor %}
                                    <div class="signup_link">
                                        Not a member? <a href='{% url "arms:register_view" %}'> Signup</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>           
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">What is ARMS?</h2>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4">Archived of Reading Materials is an Online Library where different academic and non-academic books can be found.</p>
                        <a class="btn btn-light btn-xl js-scroll-trigger" href="#contact">Contact Us</a>
                    </div>
                </div>
            </div>
        </section>
        
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">Let's Get In Touch!</h2>
                        <hr class="divider my-4" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                        <div>+23232323</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <div>arms@cit.edu</div>
                    </div>
                </div>
            </div>
        </section>
{% endif%}
         {% block content %}

    {% endblock content %}
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Archived of Reading Materials</div></div>
        </footer>
        <!-- Slick Slider -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <!-- Bootstrap core JS-->
        <!--  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script> -->
        <!-- Third party plugin JS-->
        <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script> -->
        <!-- Core theme JS-->
        <!-- <script type="text/javascript" src="{% static 'js/script.js' %}"></script> -->
        <script type="text/javascript" src="{% static 'js/homepage.js' %}"></script>
    </body>
</html>

projectarms/arms/templates/login.html
{% extends "base_1.1.html" %}
{% load static}
{% block content %}
   <div class ="login">
        <div class= "panel-transparent">
            <div class= "login-body">
                <h1>LOGIN</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="txt_field">
                        <!-- <input type="text" name="username" > -->
                        <input class="w-100" type="text" name="username" maxlength="150" required="" id="id_username">
                        <span></span>
                        <label>Username</label>
                    </div>
                    <div class="txt_field">
                        <!-- <input type="password" name="password"> -->
                        <input class="w-100" type="password" name="password" autocomplete="new-password" required="" id="id_password">
                        <span></span>
                        <label>Password</label>
                    </div>
                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>
                        {{ message }}
                    </div>
                    <div class="pass">Forgot Password?</div>
                    <input type="submit" value="LOGIN">
                    
                    <div class="signup_link">
                        Not a member? <a href='{% url "arms:register_view" %}'> Signup</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

projectarms/arms/templates/register.html
{% extends "base_1.1.html" %}
{% load static %}
{% block content %}
<div class = "d-flex justify-content-center">
	<div class ="register mt-4 mb-4" >
	   <div class= "panel-transparent">
			<div class= "register-body">
				<h1>SIGN UP</h1>
				<form method="POST" action="">
					{% csrf_token %}
					<div class="txt_field">
						<input class="w-100" type="text" name="first_name" maxlength="150" required="" id="id_first_name" autofocus>
						<span></span>
						<label>First Name</label>
					</div>
					<div class="txt_field">
						<input class="w-100" type="text" name="last_name" maxlength="150" required="" id="id_last_name">
						<span></span>
						<label>Last Name</label>
					</div>
					<div class="txt_field">
						<input class="w-100" type="text" name="username" maxlength="150" required="" id="id_username">
						<span></span>
						<label>Username</label>
					</div>
					<div class="txt_field">
						<input class="w-100" type="email" name="email" maxlength="254" required="" id="id_email">
						<span></span>
						<label>Email</label>
					</div>
					<div class="txt_field">
						<input class="w-100" type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
						<span></span>
						<label>Password</label>
					</div>
					<div class="txt_field">
						<input class="w-100" type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
						<span></span>
						<label>Confirm Password</label>
					</div>
					<div class= "form-group">
						<!-- {{form.errors}} -->
						{% if messages %}
						<ul class="messages">
						{% for message in messages %}
						<li>
						<div class="alert-success"> {{ message }}</div>
						</li>
						{% endfor %}
						</ul>
						{% endif%}
					</div>
					<div class="signup_link">
						Already have an acc? <a href='{% url "arms:landingpage_view" %}'> Sign in</a>
						&nbsp;&nbsp;
					</div>
					<div class="d-flex justify-content-center">
						<input type="submit" name="Create User">
						&nbsp;<button type="button" class="btn-cancel"  href='{% url "arms:landingpage_view" %}'>Cancel</button>
						
						
					</div>
				</form>
			</div>
		</div>     
	</div>
</div>
{% endblock content %}